language: en
pipeline:
- name: SpacyNLP
  model: en_core_web_md
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: SpacyEntityExtractor
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: SklearnIntentClassifier
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.25
  ambiguity_threshold: 0.1


policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 200
  - name: RulePolicy
    core_fallback_threshold: 0.25
    core_fallback_action_name: "action_default_fallback"